{% set name = "python-gmatelastoplasticqpot" %}
{% set version = "0.4.0" %}
{% set sha256 = "ad510dcca2ca93eafc0ebf8809cbcb16f397bd8827ad377bc6949df3b8c189f3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tdegeus/GMatElastoPlasticQPot/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win]
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - pip
    - pyxtensor
  run:
    - python

test:
  imports:
    - GMatElastoPlasticQPot

about:
  home: https://github.com/tdegeus/GMatElastoPlasticQPot
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Elasto-plastic model based on a manifold of quadratic potentials (Python wrapper).'
  description: 'Elasto-plastic model based on a manifold of quadratic potentials (Python wrapper).'
  doc_url: https://github.com/tdegeus/GMatElastoPlasticQPot
  dev_url: https://github.com/tdegeus/GMatElastoPlasticQPot

extra:
  recipe-maintainers:
    - tdegeus
