{% set name = "python-gmatelastoplasticqpot" %}
{% set version = "0.13.0" %}
{% set sha256 = "5a879143851c1d48d0951766b83f0fb5e0f35e043512316cc6ca10192ba8cddb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tdegeus/GMatElastoPlasticQPot/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - pip
    - pyxtensor
    - qpot
    - gmattensor
  run:
    - python

test:
  imports:
    - GMatElastoPlasticQPot

about:
  home: https://github.com/tdegeus/GMatElastoPlasticQPot
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Elasto-plastic model based on a manifold of quadratic potentials (Python wrapper).
  description: Elasto-plastic model based on a manifold of quadratic potentials (Python wrapper).
  doc_url: https://github.com/tdegeus/GMatElastoPlasticQPot
  dev_url: https://github.com/tdegeus/GMatElastoPlasticQPot

extra:
  recipe-maintainers:
    - tdegeus
